import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import ThemeProvider from "@/components/providers/theme-provider";

import { cn } from "@/lib/utils";
import { ModalProvider } from "@/components/providers/modal-provider";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    //required to use Auth from clerk anything wrapped in this is covered under clerk auth
    <ClerkProvider >
      <html lang="en" suppressHydrationWarning >
        <body className={cn(openSans.className, "bg-white dark:bg-[#313338]")}>
          {/* Required for shadcn theme changing  */}
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            storageKey="discord-theme"
          >
            <ModalProvider />
              {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
